### ISSUE TITLE
Calendar and clock in offer creation

### ISSUE THREAD

**Issue by zuzannawiler** [stxnext-csr/volontulo#456] opened 2016-02-23 22:45 UTC
In order to use the right format for the offer dates
As an organization
I want to have a calendar and a clock in these fields to choose a date and time precisely

**Comment by zuzannawiler** [comment] 2016-02-24 09:27
![screenshot-at-09-34-43](https://cloud.githubusercontent.com/assets/15927677/13280948/37084924-dae1-11e5-816c-ca8d9143515b.png)

**Comment by zuzannawiler** [comment] 2016-02-24 10:01
![screenshot-at-09-34-43](https://cloud.githubusercontent.com/assets/15927677/13281764/efdac054-dae5-11e5-9ea7-c4dd04efe571.png)

**Comment by Yog** [comment] 2016-02-26 11:03
this is duplicate of https://github.com/stxnext-csr/volontulo/issues/417

**Comment by magul** [comment] 2016-02-26 11:29
I'm closing it as duplicate of #417. @zuzannawiler if there is any information missing in #417, please add it there.

**Closed as completed by magul** 2016-02-26 11:29 UTC
Labels: duplicate
