### ISSUE TITLE
Editable pages

### ISSUE THREAD

**Issue by filipgorczynski** [stxnext-csr/volontulo#396] opened 2015-11-18 10:04 UTC
Make pages editable - basically Title and Body.

**Comment by Yog** [comment] 2016-01-19 13:57
This is probably important, so the static pages can actually be maintained without developer help. 
Possibly with CKEditor or other WYIWYG editor

**Comment by magul** [comment] 2016-02-26 11:25
Closed as duplicate of #467.

**Closed as completed by magul** 2016-02-26 11:25 UTC
Labels: enhancement
